### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by kevcube** [FRosner/aws-lambda-monitoring-alerting-example#1]
I'm looking to use this repository so that I don't have to reinvent the wheel and there's no license.

Github says "without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work." and this prevents me from using your codebase!

They recommend using https://choosealicense.com/, my personal favorite is the [WTFPL](http://www.wtfpl.net/)

**Comment by FRosner** [comment]
Thanks for asking! I added an Apache 2 license document.
